name: gc_coupons
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # for splash screen
  flutter_native_splash: ^2.4.0
  # for custom bottom nav bar
  stylish_bottom_bar: ^1.1.0
  awesome_icons: ^1.1.0
  # network calls
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  # for state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  # service locator
  get_it: ^7.7.0
  # for functional programming
  dartz: ^0.10.1
  # for caching and local data storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # for responsive design
  flutter_screenutil: ^5.9.3
  # for image caching
  fancy_shimmer_image: ^2.0.3
  shimmer: ^3.0.0
  # check internet connection
  connectivity_plus: ^6.0.3
  # lottie animations
  lottie: ^3.1.2
  # check equality
  equatable: ^2.0.5
  # svg images
  flutter_svg: ^2.0.10+1
  # for sharing
  share_plus: ^9.0.0
  # convert from HTML to Json
  html_unescape: ^2.0.0
  path_provider: ^2.1.3
  html: ^0.15.4
  flutter_widget_from_html: ^0.15.1
  # for opening links
  url_launcher: ^6.3.0
  #adevice preview
  device_preview: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  # for code generation
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/icons/share-nodes-solid.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
